"use client";
import { Fragment,useEffect,useState,type ReactNode } from "react";
import { getSupabaseClient } from "../lib/supabase-client";
import type { PublicArticle } from "../lib/articles";
import type { RichTextMark,RichTextNode } from "../lib/cms";
import { maldivesPublicationTime } from "../lib/publication-time";
import { TransparencyLinks } from "./TransparencyPage";

function renderNode(node:RichTextNode,key:string):ReactNode{
  if(node.type==="text"){let content:ReactNode=node.text??"";for(const mark of node.marks??[])content=renderMark(mark,content,`${key}-${mark.type}`);return <Fragment key={key}>{content}</Fragment>}
  if(node.type==="hardBreak")return <br key={key}/>;
  const children=node.content?.map((child,index)=>renderNode(child,`${key}-${index}`));
  if(node.type==="heading")return node.level===3?<h3 key={key}>{children}</h3>:<h2 key={key}>{children}</h2>;
  if(node.type==="bulletList")return <ul key={key}>{children}</ul>;
  if(node.type==="orderedList")return <ol key={key}>{children}</ol>;
  if(node.type==="listItem")return <li key={key}>{children}</li>;
  if(node.type==="blockquote")return <blockquote key={key}>{children}</blockquote>;
  if(node.type==="paragraph")return <p key={key}>{children}</p>;
  return <Fragment key={key}>{children}</Fragment>;
}
function renderMark(mark:RichTextMark,children:ReactNode,key:string){if(mark.type==="bold")return <strong key={key}>{children}</strong>;if(mark.type==="italic")return <em key={key}>{children}</em>;return <a key={key} href={mark.href} target="_blank" rel="noreferrer">{children}</a>}
function relativeTime(value:number,language:"en"|"dv"){const minutes=Math.max(0,Math.floor((Date.now()-value)/60000));if(language==="dv"){if(minutes<1)return "މިހާރު";if(minutes<60)return `${minutes} މިނިޓް ކުރިން`;const hours=Math.floor(minutes/60);if(hours<24)return `${hours} ގަޑިއިރު ކުރިން`;const days=Math.floor(hours/24);return days<7?`${days} ދުވަސް ކުރިން`:`${Math.floor(days/7)} ހަފްތާ ކުރިން`}if(minutes<1)return "Just now";if(minutes<60)return `${minutes} min ago`;const hours=Math.floor(minutes/60);if(hours<24)return `${hours} hr ago`;const days=Math.floor(hours/24);return days<7?`${days} day${days===1?"":"s"} ago`:`${Math.floor(days/7)} week${days<14?"":"s"} ago`}

export function ArticleReader({article}:{article:PublicArticle}){
  const rtl=article.language==="dv",[liked,setLiked]=useState(false),[saved,setSaved]=useState(false),[galleryIndex,setGalleryIndex]=useState(0),[message,setMessage]=useState("");
  useEffect(()=>{localStorage.setItem("kurufeetha-language",article.language)},[article.language]);
  useEffect(()=>{let active=true;(async()=>{const client=await getSupabaseClient(),session=client?(await client.auth.getSession()).data.session:null;if(!active)return;if(session){const headers={authorization:`Bearer ${session.access_token}`};const[likes,bookmarks]=await Promise.all([fetch("/api/v1/me/likes",{headers}),fetch("/api/v1/me/bookmarks",{headers})]);if(likes.ok)setLiked(((await likes.json()).items??[]).some((item:{contentType:string;contentId:string})=>item.contentType==="story"&&item.contentId===article.id));if(bookmarks.ok)setSaved(((await bookmarks.json()).items??[]).some((item:{cardId:string})=>item.cardId===article.id))}else{const likes=JSON.parse(localStorage.getItem("kurufeetha-likes")||"[]") as string[],bookmarks=JSON.parse(localStorage.getItem("kurufeetha-bookmarks")||"[]") as string[];setLiked(likes.includes(`story:${article.id}`));setSaved(bookmarks.includes(article.id))}})();return()=>{active=false}},[article.id]);
  async function update(kind:"like"|"bookmark",value:boolean){kind==="like"?setLiked(value):setSaved(value);const client=await getSupabaseClient(),session=client?(await client.auth.getSession()).data.session:null;if(session){await fetch(kind==="like"?"/api/v1/me/likes":"/api/v1/me/bookmarks",{method:"PUT",headers:{"content-type":"application/json",authorization:`Bearer ${session.access_token}`},body:JSON.stringify(kind==="like"?{contentType:"story",contentId:article.id,liked:value}:{cardId:article.id,saved:value})})}else{const key=kind==="like"?"kurufeetha-likes":"kurufeetha-bookmarks",item=kind==="like"?`story:${article.id}`:article.id,current=JSON.parse(localStorage.getItem(key)||"[]") as string[],next=value?[...new Set([...current,item])]:current.filter(entry=>entry!==item);localStorage.setItem(key,JSON.stringify(next))}}
  async function share(){const data={title:article.headline,text:article.summary,url:location.href};try{if(navigator.share){await navigator.share(data);return}}catch{return}await navigator.clipboard?.writeText(location.href);setMessage(rtl?"ލިންކް ކޮޕީ ކުރެވިއްޖެ":"Link copied");setTimeout(()=>setMessage(""),1800)}
  const gallery=article.relatedGallery,images=gallery?.images??[],currentImage=images[galleryIndex];
  return <main className="article-page" dir={rtl?"rtl":"ltr"}><header className="article-header"><a className="article-brand" href="/"><span>ކ</span><strong>KuruFeetha</strong></a><a className="article-back" href="/">{rtl?"ޚަބަރުތަކަށް":"Back to feed"}</a></header><article className="article-shell"><div className="article-category-row"><span className="article-category">{article.categoryName||article.category}</span><div className="article-actions"><button className={liked?"active":""} onClick={()=>update("like",!liked)} aria-pressed={liked} aria-label={liked?"Unlike article":"Like article"}>{liked?"♥":"♡"}</button><button onClick={share} aria-label="Share article">↗</button><button className={saved?"active":""} onClick={()=>update("bookmark",!saved)} aria-pressed={saved} aria-label={saved?"Remove bookmark":"Save article"}>{saved?"★":"☆"}</button></div></div>{(article.breaking||article.important)?<div className="article-flags">{!!article.breaking&&<span className="breaking-card-tag">{rtl?"ކުއްލި ޚަބަރު":"Breaking News"}</span>}{!!article.important&&<span className="important-badge">{rtl?"މުހިންމު":"Important"}</span>}</div>:null}<h1>{article.headline}</h1><p className="article-deck">{article.summary}</p><div className="article-publish-meta"><span>{rtl?"ޝާއިޢު ކުރީ":"Published"}</span><time dateTime={new Date(article.articlePublishedAt).toISOString()}>{maldivesPublicationTime(article.articlePublishedAt,article.language)}</time><small>{relativeTime(article.articlePublishedAt,article.language)} · {rtl?"މޯލްޑިވްސް ގަޑި":"Maldives Time"}</small></div>{article.imageUrl&&<img className="article-hero" src={article.imageUrl} alt={article.headline} loading="eager" fetchPriority="high" decoding="async"/>}<section className="article-body">{article.articleContent.content?.map((node,index)=>renderNode(node,`article-${index}`))}</section>{gallery&&currentImage&&<section className="article-gallery" aria-label={gallery.topic}><div className="article-gallery-head"><p>{rtl?"ފޮޓޯ ގެލެރީ":"Photo gallery"}</p><h2>{gallery.topic}</h2></div><div className="article-gallery-frame"><img src={currentImage.url} alt={`${gallery.topic} ${galleryIndex+1}`} loading="lazy" decoding="async"/>{images.length>1&&<><button className="gallery-prev" onClick={()=>setGalleryIndex((galleryIndex-1+images.length)%images.length)} aria-label="Previous photo">‹</button><button className="gallery-next" onClick={()=>setGalleryIndex((galleryIndex+1)%images.length)} aria-label="Next photo">›</button><span>{galleryIndex+1} / {images.length}</span></>}</div></section>}</article><footer className="article-site-footer"><div><a className="article-brand" href="/"><span>ކ</span><strong>KuruFeetha</strong></a><p>{rtl?"ދިވެހިރާއްޖޭގެ ޚަބަރު، ކުރުކޮށް.":"Maldives, in brief."}</p></div><TransparencyLinks language={article.language}/></footer>{message&&<div className="toast">{message}</div>}</main>
}
