"use client";
import { useEffect,useMemo,useState } from "react";
import type { Session } from "@supabase/supabase-js";
import { getSupabaseClient } from "../lib/supabase-client";
type Language="en"|"dv"; type Profile={id:string;email:string;displayName:string|null;role:"reader"|"admin"|"owner";preferredLanguage:Language;onboardingCompletedAt:number|null};
type Category={id:string;slug:string;nameEn:string;nameDv:string;enabled?:number;sortOrder?:number};
type Story={id:string;headline:string;summary:string;imageUrl:string|null;source:string|null;sourceUrl:string|null;category:string;categoryName:string;publishedAt:number};
type Translation={language:Language;headline:string;summary:string;status:"draft"|"published"};
type CmsStory={id:string;status:string;imageKey:string|null;sourceName:string|null;sourceUrl:string|null;categoryId:string;categoryEn:string;categoryDv:string;translations:string|Translation[]};

export function KuruFeethaApp(){const[language,setLanguage]=useState<Language>("en"),[view,setView]=useState<"feed"|"editorial">("feed"),[stories,setStories]=useState<Story[]>([]),[query,setQuery]=useState(""),[selectedCategory,setSelectedCategory]=useState("all"),[session,setSession]=useState<Session|null>(null),[profile,setProfile]=useState<Profile|null>(null),[accountOpen,setAccountOpen]=useState(false),[categories,setCategories]=useState<Category[]>([]),[follows,setFollows]=useState<string[]>([]),[loading,setLoading]=useState(true),[toast,setToast]=useState("");const token=session?.access_token,rtl=language==="dv";
  function notify(message:string){setToast(message);setTimeout(()=>setToast(""),2400)}
  useEffect(()=>{let active=true;getSupabaseClient().then(async client=>{if(!client||!active)return;setSession((await client.auth.getSession()).data.session);client.auth.onAuthStateChange((_e,s)=>setSession(s))});fetch("/api/v1/categories").then(r=>r.json()).then(d=>setCategories(d.items??[]));return()=>{active=false}},[]);
  useEffect(()=>{if(!token){setProfile(null);return}fetch("/api/v1/me",{headers:{authorization:`Bearer ${token}`}}).then(r=>r.json()).then(d=>{if(d.user){setProfile(d.user);setFollows(d.followedCategoryIds??[]);setLanguage(d.user.preferredLanguage);if(!d.user.onboardingCompletedAt)setAccountOpen(true)}})},[token]);
  useEffect(()=>{setLoading(true);fetch(`/api/v1/feed?language=${language}`,{headers:token?{authorization:`Bearer ${token}`}:{}}).then(r=>r.json()).then(d=>setStories(d.items??[])).finally(()=>setLoading(false))},[language,token]);
  const visible=useMemo(()=>stories.filter(s=>(selectedCategory==="all"||s.category===selectedCategory)&&`${s.headline} ${s.summary} ${s.source??""} ${s.categoryName}`.toLowerCase().includes(query.toLowerCase())),[stories,query,selectedCategory]);
  if(view==="editorial"&&profile&&profile.role!=="reader")return <EditorialDesk profile={profile} token={token!} onBack={()=>setView("feed")} notify={notify}/>;
  return <main className="app-shell" dir={rtl?"rtl":"ltr"}><header className="topbar"><button className="brand" onClick={()=>setView("feed")}><span className="brand-mark">ކ</span><span><strong>KuruFeetha</strong><small>{rtl?"ދިވެހިރާއްޖެ، ކުރުކޮށް.":"Maldives, in brief."}</small></span></button><div className="header-actions"><label className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={rtl?"ޚަބަރު ހޯދާ":"Search the news"}/></label><button className="language-switch" onClick={()=>setLanguage(rtl?"en":"dv")}>{rtl?"EN":"ދި"}</button><button className="avatar" onClick={()=>setAccountOpen(true)}>{profile?.displayName?.slice(0,2).toUpperCase()||"IN"}</button></div></header>
  <nav className="category-rail" aria-label={rtl?"ޚަބަރުގެ ބައިތައް":"News categories"}><button className={selectedCategory==="all"?"active":""} aria-pressed={selectedCategory==="all"} onClick={()=>setSelectedCategory("all")}>{rtl?"ހުރިހާ":"For you"}</button>{categories.map(c=><button key={c.id} className={selectedCategory===c.slug?"active":""} aria-pressed={selectedCategory===c.slug} onClick={()=>setSelectedCategory(c.slug)}>{rtl?c.nameDv:c.nameEn}</button>)}</nav><section className="feed-head"><div><p className="eyebrow">KURUFEETHA</p><h1>{rtl?"މިއަދުގެ ޚުލާޞާ":"Today’s briefing"}</h1></div><span className="story-count">{visible.length} {rtl?"ޚަބަރު":"stories"}</span></section>
  <section className="story-feed">{loading?<div className="empty-state"><p>Loading…</p></div>:visible.map((s,i)=><article className="story-card" key={s.id}>{s.imageUrl?<img className="story-photo" src={s.imageUrl} alt=""/>:<div className="story-visual"><span className="visual-number">{String(i+1).padStart(2,"0")}</span><div className="visual-watermark">ކުރު</div></div>}<div className="story-content"><div className="story-meta"><span className="pill">{s.categoryName||s.category}</span></div><h2>{s.headline}</h2><p className="summary">{s.summary}</p><div className="story-footer">{s.sourceUrl?<a href={s.sourceUrl} target="_blank" rel="noreferrer"><span>{s.source}</span><strong>{rtl?"މުޅި ޚަބަރު ކިޔާ":"Read full story"} ↗</strong></a>:<span/>}<div className="card-actions"><button onClick={()=>{navigator.clipboard?.writeText(location.href);notify("Link copied")}}>↗</button></div></div></div></article>)}{!loading&&!visible.length&&<div className="empty-state"><span>ކ</span><p>{rtl?"މި ބައިގައި ޚަބަރެއް ނެތް.":"No published stories yet."}</p></div>}</section>
  <nav className="bottom-nav"><button className="active"><span>◉</span>{rtl?"ޚަބަރު":"Briefing"}</button>{profile?.role!=="reader"&&profile&&<button onClick={()=>setView("editorial")}><span>✦</span>CMS</button>}<button onClick={()=>setAccountOpen(true)}><span>○</span>{profile?"Account":"Sign in"}</button></nav>{accountOpen&&<AccountPanel session={session} profile={profile} categories={categories} follows={follows} onFollows={setFollows} onClose={()=>setAccountOpen(false)} notify={notify}/>} {toast&&<div className="toast">{toast}</div>}</main>}

function EditorialDesk({profile,token,onBack,notify}:{profile:Profile;token:string;onBack:()=>void;notify:(s:string)=>void}){const[section,setSection]=useState<"stories"|"categories">("stories"),[items,setItems]=useState<CmsStory[]>([]),[categories,setCategories]=useState<Category[]>([]),[editing,setEditing]=useState<CmsStory|null>(null);const headers={authorization:`Bearer ${token}`};
  async function load(){const[a,b]=await Promise.all([fetch("/api/v1/admin/cards",{headers}).then(r=>r.json()),fetch("/api/v1/admin/categories",{headers}).then(r=>r.json())]);setItems(a.items??[]);setCategories(b.items??[])}useEffect(()=>{load()},[]);
  return <main className="editorial-shell"><aside className="editorial-nav"><button className="brand inverted" onClick={onBack}><span className="brand-mark">ކ</span><span><strong>KuruFeetha</strong><small>Manual CMS</small></span></button><p className="nav-label">CONTENT</p><button className={`nav-item ${section==="stories"?"active":""}`} onClick={()=>setSection("stories")}>▦ Stories</button><button className={`nav-item ${section==="categories"?"active":""}`} onClick={()=>setSection("categories")}>◎ Categories</button><div className="editor-profile"><span>{profile.displayName?.slice(0,2).toUpperCase()}</span><div><strong>{profile.displayName||profile.email}</strong><small>{profile.role}</small></div></div></aside><section className="editorial-main">{section==="categories"?<CategoryManager items={categories} token={token} reload={load} notify={notify}/>:editing?<StoryEditor story={editing} categories={categories} token={token} onDone={()=>{setEditing(null);load()}} notify={notify}/>:<><header className="desk-header"><div><p className="eyebrow">EDITORIAL CMS</p><h1>Stories</h1></div><button className="primary-action compact" onClick={()=>setEditing({id:"",status:"draft",imageKey:null,sourceName:null,sourceUrl:null,categoryId:categories[0]?.id,categoryEn:"",categoryDv:"",translations:[]})}>New story</button></header><div className="queue-list">{items.map(item=>{const ts=typeof item.translations==="string"?JSON.parse(item.translations):item.translations;return <article className="queue-item" key={item.id}><div className="source-token">ކ</div><div className="queue-copy"><div><span>{item.categoryEn}</span><span>·</span><span>{item.status}</span></div><h3>{ts.find((t:Translation)=>t.language==="en")?.headline||ts.find((t:Translation)=>t.language==="dv")?.headline||"Untitled"}</h3><p>{ts.map((t:Translation)=>`${t.language.toUpperCase()}: ${t.status}`).join(" · ")}</p></div><div className="queue-actions"><button onClick={()=>setEditing({...item,translations:ts})}>Edit →</button></div></article>})}</div></>}</section></main>}

function StoryEditor({story,categories,token,onDone,notify}:{story:CmsStory;categories:Category[];token:string;onDone:()=>void;notify:(s:string)=>void}){const list=typeof story.translations==="string"?JSON.parse(story.translations):story.translations;const find=(l:Language)=>list.find((t:Translation)=>t.language===l);const[form,setForm]=useState({categoryId:story.categoryId||categories[0]?.id||"",imageKey:story.imageKey||"",imageUrl:story.imageKey?`/api/v1/media/${story.imageKey}`:"",sourceName:story.sourceName||"",sourceUrl:story.sourceUrl||"",en:{headline:find("en")?.headline||"",summary:find("en")?.summary||"",published:find("en")?.status==="published"},dv:{headline:find("dv")?.headline||"",summary:find("dv")?.summary||"",published:find("dv")?.status==="published"}}),[busy,setBusy]=useState(false);const words=(s:string)=>s.trim()?s.trim().split(/\s+/u).length:0;
  async function upload(file:File){setBusy(true);const data=new FormData();data.set("file",file);const r=await fetch("/api/v1/admin/media",{method:"POST",headers:{authorization:`Bearer ${token}`},body:data}),d=await r.json();if(r.ok)setForm(f=>({...f,imageKey:d.key,imageUrl:d.url}));else notify(d.error?.message||"Upload failed");setBusy(false)}
  async function save(){setBusy(true);const method=story.id?"PATCH":"POST",url=story.id?`/api/v1/admin/cards/${story.id}`:"/api/v1/admin/cards";const body={categoryId:form.categoryId,imageKey:form.imageKey||undefined,sourceName:form.sourceName,sourceUrl:form.sourceUrl,translations:{en:form.en,dv:form.dv}};const r=await fetch(url,{method,headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:JSON.stringify(body)}),d=await r.json();if(!r.ok){notify(d.error?.message||"Could not save");setBusy(false);return}const id=story.id||d.id;for(const language of ["en","dv"] as const){if(form[language].headline)await fetch(`/api/v1/admin/cards/${id}/publish`,{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:JSON.stringify({language,published:form[language].published})})}notify("Story saved");onDone()}
  return <><header className="desk-header"><div><p className="eyebrow">{story.id?"EDIT STORY":"NEW STORY"}</p><h1>News card</h1></div><button className="secondary" onClick={onDone}>Back</button></header><div className="cms-form"><label>Photo<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></label>{form.imageUrl&&<img className="cms-preview-image" src={form.imageUrl} alt="Preview"/>}<label>Category<select value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})}>{categories.filter(c=>c.enabled!==0).map(c=><option value={c.id} key={c.id}>{c.nameEn} · {c.nameDv}</option>)}</select></label><div className="form-grid"><LanguageFields label="English" value={form.en} words={words(form.en.summary)} onChange={v=>setForm({...form,en:v})}/><LanguageFields label="ދިވެހި" rtl value={form.dv} words={words(form.dv.summary)} onChange={v=>setForm({...form,dv:v})}/></div><div className="form-grid"><label>Source name (optional)<input value={form.sourceName} onChange={e=>setForm({...form,sourceName:e.target.value})}/></label><label>Source URL (optional)<input type="url" value={form.sourceUrl} onChange={e=>setForm({...form,sourceUrl:e.target.value})}/></label></div><button className="primary-action" disabled={busy||!form.imageKey||(!form.en.headline&&!form.dv.headline)||words(form.en.summary)>60||words(form.dv.summary)>60} onClick={save}>{busy?"Saving…":"Save story"}</button>{story.id&&<button className="danger-action" onClick={async()=>{await fetch(`/api/v1/admin/cards/${story.id}`,{method:"DELETE",headers:{authorization:`Bearer ${token}`}});onDone()}}>Archive story</button>}</div></>}
function LanguageFields({label,rtl,value,words,onChange}:{label:string;rtl?:boolean;value:{headline:string;summary:string;published:boolean};words:number;onChange:(v:typeof value)=>void}){return <fieldset dir={rtl?"rtl":"ltr"}><legend>{label}</legend><label>Title<input value={value.headline} maxLength={180} onChange={e=>onChange({...value,headline:e.target.value})}/></label><label>Summary<textarea rows={6} value={value.summary} onChange={e=>onChange({...value,summary:e.target.value})}/><small className={words>60?"over":""}>{words}/60 words</small></label><label className="publish-check"><input type="checkbox" checked={value.published} onChange={e=>onChange({...value,published:e.target.checked})}/> Publish this language</label></fieldset>}

function CategoryManager({items,token,reload,notify}:{items:Category[];token:string;reload:()=>void;notify:(s:string)=>void}){const[en,setEn]=useState(""),[dv,setDv]=useState("");async function create(){const r=await fetch("/api/v1/admin/categories",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:JSON.stringify({nameEn:en,nameDv:dv})});if(r.ok){setEn("");setDv("");reload()}else notify("Could not create category")}async function patch(id:string,body:object){await fetch(`/api/v1/admin/categories/${id}`,{method:"PATCH",headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:JSON.stringify(body)});reload()}return <><header className="desk-header"><div><p className="eyebrow">EDITORIAL CMS</p><h1>Categories</h1></div></header><div className="category-create"><input placeholder="English name" value={en} onChange={e=>setEn(e.target.value)}/><input dir="rtl" placeholder="ދިވެހި ނަން" value={dv} onChange={e=>setDv(e.target.value)}/><button onClick={create}>Add category</button></div><div className="user-list">{items.map((c,i)=><article className="user-row" key={c.id}><div><strong>{c.nameEn}</strong><small dir="rtl">{c.nameDv}</small></div><div><button onClick={()=>{const nameEn=prompt("English category name",c.nameEn),nameDv=prompt("Thaana category name",c.nameDv);if(nameEn&&nameDv)patch(c.id,{nameEn,nameDv})}}>Rename</button><button onClick={()=>patch(c.id,{sortOrder:Math.max(0,i-1)})}>↑</button><button onClick={()=>patch(c.id,{enabled:!c.enabled})}>{c.enabled?"Disable":"Enable"}</button></div></article>)}</div></>}

function AccountPanel({session,profile,categories,follows,onFollows,onClose,notify}:{session:Session|null;profile:Profile|null;categories:Category[];follows:string[];onFollows:(v:string[])=>void;onClose:()=>void;notify:(s:string)=>void}){const[email,setEmail]=useState("");async function signIn(provider?:"google"){const c=await getSupabaseClient();if(!c)return notify("Sign-in awaits Supabase configuration");if(provider)await c.auth.signInWithOAuth({provider,options:{redirectTo:location.origin}});else{await c.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin}});notify("Check your email")}}async function save(){if(!session)return;await fetch("/api/v1/me/categories",{method:"PUT",headers:{"content-type":"application/json",authorization:`Bearer ${session.access_token}`},body:JSON.stringify({categoryIds:follows})});onClose()}return <div className="modal-backdrop" onMouseDown={onClose}><section className="account-panel" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={onClose}>×</button>{profile?<><p className="eyebrow">{profile.role}</p><h2>{profile.displayName||profile.email}</h2><h3>Topics you follow</h3><div className="preference-grid">{categories.map(c=><label key={c.id}><input type="checkbox" checked={follows.includes(c.id)} onChange={()=>onFollows(follows.includes(c.id)?follows.filter(x=>x!==c.id):[...follows,c.id])}/>{c.nameEn} · {c.nameDv}</label>)}</div><button className="primary-action" onClick={save}>Save preferences</button><div className="account-actions"><button onClick={async()=>{await(await getSupabaseClient())?.auth.signOut();onClose()}}>Sign out</button></div></>:<><h2>Sign in</h2><div className="oauth-row"><button onClick={()=>signIn("google")}>Google</button></div><div className="email-signin"><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/><button onClick={()=>signIn()}>Email link</button></div></>}</section></div>}
