"use client";
import{useState}from"react";
import{getSupabaseClient}from"../lib/supabase-client";
import type{ArticleContentType}from"../lib/authors";

const options:[ArticleContentType,string][]=[["news","News"],["opinion","Opinion"],["editorial","Editorial"],["press_release","Press Release"]];
async function freshToken(fallback:string){const client=await getSupabaseClient();if(!client)return fallback;const session=(await client.auth.getSession()).data.session;if(!session?.access_token)throw new Error("Please sign in again to continue.");return session.access_token}

export function SafeContentTypeEditor({cardId,translationId,language,currentType,token,onSaved}:{cardId:string;translationId:string;language:"en"|"dv";currentType:ArticleContentType|null;token:string;onSaved:(value:ArticleContentType)=>void}){
  const[selected,setSelected]=useState<ArticleContentType|null>(currentType),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  async function save(){if(!selected||selected===currentType||busy)return;setBusy(true);setMessage("");try{const accessToken=await freshToken(token),response=await fetch(`/api/v1/admin/cards/${cardId}/content-type`,{method:"PATCH",headers:{"content-type":"application/json",authorization:`Bearer ${accessToken}`},body:JSON.stringify({translationId,contentType:selected,expectedContentType:currentType})}),result=await response.json().catch(()=>null);if(response.status===409)throw new Error("This value changed after the story was loaded. Refresh the story before trying again.");if(!response.ok)throw new Error(result?.error?.message||"Could not update content type");onSaved(result.contentType);setMessage(`${language.toUpperCase()} content type updated without republishing.`)}catch(error){setMessage((error as Error).message)}finally{setBusy(false)}}
  return <div className="safe-content-type-editor" dir="ltr"><div><strong>Safe content-type update · {language.toUpperCase()}</strong><small>Changes only the classification. It does not republish this card or article.</small></div><label>Current value<strong>{options.find(([value])=>value===currentType)?.[1]??"Not classified"}</strong></label><select aria-label={`${language.toUpperCase()} safe content type`} value={selected??""} onChange={event=>setSelected((event.target.value||null) as ArticleContentType|null)}><option value="">Select classification</option>{options.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select><button type="button" className="secondary compact" disabled={busy||!selected||selected===currentType} onClick={save}>{busy?"Updating…":"Update content type only"}</button>{message&&<small role="status" className={message.includes("updated without")?"":"attribution-warning"}>{message}</small>}</div>;
}
