import assert from"node:assert/strict";
import{readFile}from"node:fs/promises";
import{DatabaseSync}from"node:sqlite";
import test from"node:test";
import{ContentTypeUpdateError,parseContentTypeUpdate,updateContentTypeOnly}from"../app/lib/content-type-update.ts";

class Statement{constructor(db,sql){this.db=db;this.sql=sql;this.values=[]}bind(...values){this.values=values;return this}async first(){return this.db.prepare(this.sql).get(...this.values)??null}run(){return this.db.prepare(this.sql).run(...this.values)}}
class TestDatabase{constructor(){this.sqlite=new DatabaseSync(":memory:");this.sqlite.exec(`CREATE TABLE news_cards(id TEXT PRIMARY KEY,status TEXT,category_id TEXT,published_at INTEGER,updated_at INTEGER);CREATE TABLE news_card_translations(id TEXT PRIMARY KEY,card_id TEXT,language TEXT,headline TEXT,summary TEXT,article_content TEXT,content_type TEXT,review_status TEXT,published_at INTEGER,article_status TEXT,article_published_at INTEGER,updated_at INTEGER);CREATE TABLE article_credits(id TEXT,translation_id TEXT,author_id TEXT,role TEXT,sort_order INTEGER);CREATE TABLE audit_events(id TEXT,actor_id TEXT,action TEXT,entity_type TEXT,entity_id TEXT,before TEXT,after TEXT,created_at INTEGER);INSERT INTO news_cards VALUES('card','published','category',1000,1100);INSERT INTO news_card_translations VALUES('en','card','en','English headline','English summary','{"type":"doc"}',NULL,'published',2000,'published',3000,3100);INSERT INTO news_card_translations VALUES('dv','card','dv','Dhivehi headline','Dhivehi summary','{"type":"doc"}',NULL,'published',2001,'published',3001,3101);INSERT INTO article_credits VALUES('credit','en','author','author',0);`)}prepare(sql){return new Statement(this.sqlite,sql)}async batch(statements){this.sqlite.exec("BEGIN");try{const results=statements.map(statement=>{const result=statement.run();return{meta:{changes:Number(result.changes)}}});this.sqlite.exec("COMMIT");return results}catch(error){this.sqlite.exec("ROLLBACK");throw error}}}

const snapshot=db=>({card:db.sqlite.prepare("SELECT * FROM news_cards WHERE id='card'").get(),en:db.sqlite.prepare("SELECT * FROM news_card_translations WHERE id='en'").get(),dv:db.sqlite.prepare("SELECT * FROM news_card_translations WHERE id='dv'").get(),credits:db.sqlite.prepare("SELECT * FROM article_credits ORDER BY id").all()});

test("content-type-only mutation preserves every publication and editorial field",async()=>{const db=new TestDatabase(),plain=value=>JSON.parse(JSON.stringify(value)),before=plain(snapshot(db)),input=parseContentTypeUpdate({translationId:"en",contentType:"news",expectedContentType:null},"card"),result=await updateContentTypeOnly(db,input,"admin",4000,"audit");const after=plain(snapshot(db));assert.equal(after.en.content_type,"news");assert.deepEqual({...after.en,content_type:null},before.en);assert.deepEqual(after.card,before.card);assert.deepEqual(after.dv,before.dv);assert.deepEqual(after.credits,before.credits);assert.deepEqual(result,{cardId:"card",translationId:"en",language:"en",previousContentType:null,contentType:"news"});const audit=db.sqlite.prepare("SELECT * FROM audit_events").get();assert.equal(audit.action,"translation.content_type_updated");assert.equal(audit.actor_id,"admin");assert.deepEqual(JSON.parse(audit.before),{translationId:"en",cardId:"card",language:"en",contentType:null});assert.deepEqual(JSON.parse(audit.after),{translationId:"en",cardId:"card",language:"en",contentType:"news",operation:"content_type_update"})});

test("all four explicit values are accepted while null and unknown values are rejected",()=>{for(const contentType of["news","opinion","editorial","press_release"])assert.equal(parseContentTypeUpdate({translationId:"en",contentType,expectedContentType:null},"card").contentType,contentType);for(const contentType of[null,"review",""])assert.throws(()=>parseContentTypeUpdate({translationId:"en",contentType,expectedContentType:null},"card"),error=>error instanceof ContentTypeUpdateError&&error.code==="INVALID_CONTENT_TYPE")});

test("stale updates conflict without changing data or writing an audit event",async()=>{const db=new TestDatabase(),before=snapshot(db);await assert.rejects(()=>updateContentTypeOnly(db,{cardId:"card",translationId:"en",contentType:"opinion",expectedContentType:"news"},"admin",4000,"audit"),error=>error instanceof ContentTypeUpdateError&&error.status===409&&error.code==="STALE_CONTENT_TYPE");assert.deepEqual(snapshot(db),before);assert.equal(db.sqlite.prepare("SELECT COUNT(*) count FROM audit_events").get().count,0)});

test("a selected translation changes without silently changing its sibling",async()=>{const db=new TestDatabase();await updateContentTypeOnly(db,{cardId:"card",translationId:"dv",contentType:"editorial",expectedContentType:null},"admin",4000,"audit-dv");assert.equal(db.sqlite.prepare("SELECT content_type FROM news_card_translations WHERE id='dv'").get().content_type,"editorial");assert.equal(db.sqlite.prepare("SELECT content_type FROM news_card_translations WHERE id='en'").get().content_type,null)});

test("endpoint and CMS use existing admin auth with an explicit non-republishing action",async()=>{const[route,ui,shell,sitemap]=await Promise.all([readFile(new URL("../app/api/v1/admin/cards/[id]/content-type/route.ts",import.meta.url),"utf8"),readFile(new URL("../app/components/SafeContentTypeEditor.tsx",import.meta.url),"utf8"),readFile(new URL("../app/components/KuruFeethaApp.tsx",import.meta.url),"utf8"),readFile(new URL("../worker/seo-sitemaps.ts",import.meta.url),"utf8")]);assert.match(route,/requireAdmin\(request\)/);assert.match(route,/authErrorResponse/);assert.match(ui,/Update content type only/);assert.match(ui,/does not republish/);assert.match(ui,/response\.status===409/);assert.match(shell,/SafeContentTypeEditor/);assert.match(sitemap,/legacyNullEligible:true/);assert.match(sitemap,/t\.content_type IS NULL/)});
