import { env } from "cloudflare:workers";
import { authErrorResponse, requireAdmin } from "../../../../../lib/auth";

export const dynamic="force-dynamic";
type Body={topicEn?:string;topicDv?:string;publishedEn?:boolean;publishedDv?:boolean;categoryId?:string;relatedStoryEnId?:string|null;relatedStoryDvId?:string|null};

export async function PATCH(request:Request,context:{params:Promise<{id:string}>}){let actor;try{actor=await requireAdmin(request)}catch(error){return authErrorResponse(error)}const{id}=await context.params,body=await request.json().catch(()=>null) as Body|null,en=body?.topicEn?.trim()||null,dv=body?.topicDv?.trim()||null;if(!body?.categoryId||(!en&&!dv)||(body.publishedEn&&!en)||(body.publishedDv&&!dv)||(en?.length??0)>180||(dv?.length??0)>180)return Response.json({error:{code:"INVALID_GALLERY",message:"Add valid topics, publication choices and a category"}},{status:400});const db=(env as unknown as{DB:D1Database}).DB;if(!await db.prepare("SELECT 1 FROM galleries WHERE id=?").bind(id).first())return Response.json({error:{code:"NOT_FOUND"}},{status:404});if(!await db.prepare("SELECT 1 FROM categories WHERE id=? AND enabled=1").bind(body.categoryId).first())return Response.json({error:{code:"INVALID_CATEGORY"}},{status:400});for(const storyId of[body.relatedStoryEnId,body.relatedStoryDvId])if(storyId&&!await db.prepare("SELECT 1 FROM news_cards WHERE id=? AND status!='archived'").bind(storyId).first())return Response.json({error:{code:"INVALID_STORY"}},{status:400});const now=Date.now(),published=!!(body.publishedEn||body.publishedDv);await db.batch([db.prepare("UPDATE galleries SET topic=?,language=?,topic_en=?,topic_dv=?,published_en=?,published_dv=?,category_id=?,related_story_id=?,related_story_en_id=?,related_story_dv_id=?,status=?,published_at=CASE WHEN ? THEN COALESCE(published_at,?) ELSE NULL END,updated_at=? WHERE id=?").bind(en||dv,en?"en":"dv",en,dv,body.publishedEn?1:0,body.publishedDv?1:0,body.categoryId,body.relatedStoryEnId||body.relatedStoryDvId||null,body.relatedStoryEnId||null,body.relatedStoryDvId||null,published?"published":"draft",published?1:0,now,now,id),db.prepare("INSERT INTO audit_events (id,actor_id,action,entity_type,entity_id,created_at) VALUES (?,?,?,?,?,?)").bind(crypto.randomUUID(),actor.id,"gallery.updated","gallery",id,now)]);return Response.json({id})}

export async function DELETE(request:Request,context:{params:Promise<{id:string}>}){try{await requireAdmin(request)}catch(error){return authErrorResponse(error)}const{id}=await context.params,now=Date.now();await(env as unknown as{DB:D1Database}).DB.prepare("UPDATE galleries SET status='archived',published_en=0,published_dv=0,updated_at=? WHERE id=?").bind(now,id).run();return Response.json({id,status:"archived"})}
